# Generated by Django 4.0 on 2022-01-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentbest',
            options={'verbose_name_plural': '4. CurrentBests'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': '1. Items'},
        ),
        migrations.AlterModelOptions(
            name='iteminstance',
            options={'verbose_name_plural': '3. ItemsInstances'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name_plural': '5. Recipes'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name_plural': '2. Stores'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name_plural': '6. Trips'},
        ),
    ]
