# Generated by Django 4.0 on 2022-01-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_alter_currentbest_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
